"""Dockerfile generator for production-ready containers."""

from pathlib import Path

from ..analyzer.models import AppAnalysis


def generate_dockerfile(analysis: AppAnalysis) -> str:
    """
    Generate a production-ready multi-stage Dockerfile.

    Args:
        analysis: Application analysis results

    Returns:
        Dockerfile content as a string
    """
    # Determine framework-specific settings
    framework = analysis.framework.name.lower() if analysis.framework else "script"
    entry_point = analysis.framework.entry_point if analysis.framework else "app.py"

    # Framework-specific configurations
    # For ASGI/WSGI frameworks, use hardened_entry.py (generated middleware wrapper)
    # instead of the original app module. This wraps the app with security middleware
    # without modifying the original source code.
    config = {
        "fastapi": {
            "port": 8000,
            "command": "uvicorn hardened_entry:app --host 0.0.0.0 --port 8000",
            "healthcheck": "curl -f http://localhost:8000/healthz || exit 1",
        },
        "streamlit": {
            "port": 8501,
            "command": f"streamlit run {entry_point} --server.port 8501 --server.address 0.0.0.0",
            "healthcheck": "curl -f http://localhost:8501/_stcore/health || exit 1",
        },
        "gradio": {
            "port": 7860,
            "command": f"python {entry_point}",
            "healthcheck": "curl -f http://localhost:7860/healthz || exit 1",
        },
        "flask": {
            "port": 5000,
            "command": "gunicorn -w 4 -b 0.0.0.0:5000 hardened_entry:app",
            "healthcheck": "curl -f http://localhost:5000/healthz || exit 1",
        },
        "script": {
            "port": 8000,
            "command": f"python {entry_point}",
            "healthcheck": "curl -f http://localhost:8000/healthz || exit 1",
        },
    }

    settings = config.get(framework, config["script"])

    project_root = Path(analysis.project_path)
    lock_file = project_root / "requirements.lock"
    req_file = project_root / "requirements.txt"
    pyproject = project_root / "pyproject.toml"

    if lock_file.exists():
        dep_copy = "COPY requirements.lock ."
        dep_install = "pip install --no-cache-dir -r requirements.lock"
        pre_install_copy = ""
    elif req_file.exists():
        dep_copy = "COPY requirements.txt ."
        dep_install = "pip install --no-cache-dir -r requirements.txt"
        pre_install_copy = ""
    elif pyproject.exists():
        dep_copy = "COPY pyproject.toml ."
        pre_install_copy = "COPY . ."
        dep_install = "pip install --no-cache-dir ."
    else:
        dep_copy = "COPY requirements.txt ."
        pre_install_copy = ""
        dep_install = "pip install --no-cache-dir -r requirements.txt"

    dockerfile = f'''# Multi-stage production Dockerfile
# Generated by harden v0.1.0
# https://github.com/vizops/harden

# ============================================================================
# Builder Stage: Install dependencies
# ============================================================================
FROM python:3.11-slim AS builder

WORKDIR /build

# Install system dependencies needed for building Python packages
RUN apt-get update && apt-get install -y --no-install-recommends \\
    gcc \\
    g++ \\
    && rm -rf /var/lib/apt/lists/*

# Copy dependency manifest(s) first for better layer caching
{dep_copy}
{pre_install_copy}

# Install Python dependencies in a virtual environment
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install --no-cache-dir --upgrade pip && \\
    {dep_install}

# ============================================================================
# Runtime Stage: Minimal production image
# ============================================================================
FROM python:3.11-slim

# Install runtime dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    curl \\
    && rm -rf /var/lib/apt/lists/*

# Create non-root user for running the application
# Using fixed UID 1000 for consistency across environments
RUN groupadd -g 1000 appuser && \\
    useradd -r -u 1000 -g appuser -m -d /home/appuser -s /bin/bash appuser

# Set working directory
WORKDIR /app

# Copy virtual environment from builder stage
COPY --from=builder /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Copy application code
# Note: .env files are excluded via .dockerignore - never bake secrets into images
COPY --chown=appuser:appuser . .

# Create log directory with proper permissions
RUN mkdir -p /var/log/app && chown -R appuser:appuser /var/log/app

# Copy and make entrypoint executable
COPY --chown=appuser:appuser entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# Switch to non-root user
USER appuser

# Expose application port
EXPOSE {settings["port"]}

# Health check configuration
# This allows Docker/K8s to detect if the container is healthy
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \\
    CMD {settings["healthcheck"]}

# Labels for container metadata
LABEL maintainer="devops@vizops.ai" \\
      harden-version="0.1.0" \\
      framework="{framework}" \\
      description="Production-hardened {framework} application"

# Set Python to run in unbuffered mode (logs appear immediately)
ENV PYTHONUNBUFFERED=1

# Default command (can be overridden)
CMD ["/app/entrypoint.sh"]
'''

    return dockerfile


def generate_dockerignore(analysis: AppAnalysis) -> str:
    """
    Generate a .dockerignore file to exclude unnecessary files from Docker build context.

    Args:
        analysis: Application analysis results

    Returns:
        .dockerignore content as a string
    """
    dockerignore = '''# Harden-generated .dockerignore
# Excludes files from Docker build context for security and efficiency

# ============================================================================
# Security: Never include secrets or credentials
# ============================================================================
.env
.env.*
*.env
.env.local
.env.production
.env.staging
secrets/
credentials/
*.pem
*.key
*.crt
*.p12
*.pfx
.aws/
.gcp/
.azure/

# ============================================================================
# Development files
# ============================================================================
.git/
.gitignore
.github/
.gitlab-ci.yml
.vscode/
.idea/
*.swp
*.swo
*~

# Python
__pycache__/
*.py[cod]
*$py.class
.pytest_cache/
.coverage
.tox/
.mypy_cache/
.ruff_cache/
*.egg-info/
dist/
build/
venv/
env/
.venv/

# Node.js (if applicable)
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Documentation
README.md
CHANGELOG.md
LICENSE
docs/
*.md

# Testing
tests/
test/
*_test.py
test_*.py

# Build artifacts
*.log
*.sqlite
*.db
.DS_Store
Thumbs.db

# CI/CD
.circleci/
.travis.yml
azure-pipelines.yml
Jenkinsfile

# Docker
Dockerfile.dev
docker-compose.dev.yml
.dockerignore
'''

    return dockerignore
